Pseudo inverse....

In [1]:
import numpy as np

In [3]:
A = np.array([[-1, 2], [3, -2], [5, 7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

Numpy SVD method

In [4]:
U, d, VT = np.linalg.svd(A)

To create D+, we first invert the non-zero values of d:

In [5]:
D = np.diag(d)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

In [ ]:
1/8.669

In [ ]:
1/4.104

Then we would take the transpose of the resulting matrix.
Because D is a diagonal matrix, this can, however, be done in a single step by inverting D:

In [6]:
Dinv = np.linalg.inv(D)
Dinv

array([[0.1153511 , 0.        ],
       [0.        , 0.24364718]])

Fix D+, cause D must have the same dimensions as AT in order for matrix multiplication to be possible

In [8]:
Dplus = np.concatenate((Dinv, np.array([[0, 0]]).T), axis=1)
Dplus

array([[0.1153511 , 0.        , 0.        ],
       [0.        , 0.24364718, 0.        ]])

In [11]:
Aplus = VT.T @ Dplus @ U.T
Aplus

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])

In [12]:
np.linalg.pinv(A)

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])