Singular Value Decomposition (SVD)

In [1]:
import numpy as np

In [2]:
A = np.array([[-1, 2], [3, -2], [5, 7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [3]:
U, d, VT = np.linalg.svd(A) # V is already transposed

In [4]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [5]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [6]:
d

array([8.66918448, 4.10429538])

In [7]:
np.diag(d)

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

D must have the same dimensions as A for matrix multiplication to be possible:

In [8]:
D = np.concatenate((np.diag(d), [[0, 0]]), axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [11]:
A_reconstructed = U @ D @ VT
A_reconstructed

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])